#!/bin/bash
#SBATCH --time=00:00:50   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=205M   # memory per CPU core
#SBATCH --qos=test


# Set the max number of threads to use for programs using OpenMP. Should be <= ppn. Does nothing if the program doesn't use OpenMP.
export OMP_NUM_THREADS=$SLURM_CPUS_ON_NODE


chmod 755 /fslhome/scandium/unixstuff/backups/v.txt
chmod 755 /fslhome/scandium/unixstuff/backups/w.txt
#mapfile -t v < v.txt
#mapfile -t w < w.txt

v=()
w=()
while IFS= read -r line
do
  v+=("$line")
done < v.txt

while IFS= read -r line
do
  w+=("$line")
done < w.txt


#v=(1 2 3 4 5)
#w=(1 2 3 4 5)
dot=0
len=${#v[@]}
n=$(($len-1))
echo $n
for ((i=0;i<=n;i++))
do
 dot=$(($dot+${v[$i]}*${w[$i]}))
done
echo $dot


