#!/bin/bash
cd
re=$(jot -r 1  1 5767)
echo $re
var=$(sed -n "$re"p ~/anaconda3/pkgs/networkx-2.4-py_0/share/doc/networkx-2.4/examples/graph/words_dat.txt)
#var=sed "$r" ~/anaconda3/pkgs/networkx-2.4-py_0/share/doc/networkx-2.4/examples/graph/words_dat.txt
 
echo $var
