#!/bin/bash
list="1A 1B 1C 2A 2B 2C 3A 3B 3C"
i=0
x=0
o=0
i=0
PS3="_|_1_|_2_|_3_|"$'\n'"
_A|___|___|___|"$'\n'"
_B|___|___|___|"$'\n'"
_C|___|___|___|"

select ch in $list
do
 if [ $i -et 0 ]
 then
   PS3="_|_1_|_2_|_3_|"$'\n'"
_A|___|___|___|"$'\n'"
_B|___|___|___|"$'\n'"
_C|___|___|___|"
   if [ $ch = 1A ]
   then
     x="$x $ch"
     list="1B 1C 2A 2B 2C 3A 3B 3C"
     r=


